import {useRef, useState} from 'react'
import {Pressable, TextInput, View} from 'react-native'
import {
  RichText,
  TenTapStartKit,
  UnderlineBridge as DefaultUnderlineBridge,
  useBridgeState,
  useEditorBridge,
} from '@10play/tentap-editor'
import {type AtUriString} from '@atproto/syntax'
import {msg} from '@lingui/core/macro'
import {useLingui} from '@lingui/react'
import {Trans} from '@lingui/react/macro'
import {useNavigation} from '@react-navigation/native'
import {useQueryClient} from '@tanstack/react-query'

import {type ArticleEditRef, publishArticle} from '#/lib/api/articles'
import {uploadBlob} from '#/lib/api/upload-blob'
import {SUNNAHSKY_SERVICE} from '#/lib/constants'
import {useRequireStrikerForArticleAuthoring} from '#/lib/hooks/useRequireStrikerForArticleAuthoring'
import {openPicker} from '#/lib/media/picker'
import {
  type CommonNavigatorParams,
  type NativeStackScreenProps,
  type NavigationProp,
} from '#/lib/routes/types'
import {niceDate} from '#/lib/strings/time'
import {
  DOCUMENT_RQKEY,
  type LoadedArticleDocument,
  RQKEY,
  useArticleDocumentQuery,
  waitForArticleIndexed,
} from '#/state/queries/articles'
import {useAppviewClient, usePdsClient, useSession} from '#/state/session'
import {atoms as a, useBreakpoints, useTheme, web} from '#/alf'
import {Button, ButtonText} from '#/components/Button'
import {TimesLarge_Stroke2_Corner0_Rounded as XIcon} from '#/components/icons/Times'
import {Loader} from '#/components/Loader'
import {Portal} from '#/components/Portal'
import * as Prompt from '#/components/Prompt'
import * as Toast from '#/components/Toast'
import {Text} from '#/components/Typography'
import {type site} from '#/lexicons'
import {ContentBridge} from './bridges/content'
import {HonorificBridge} from './bridges/honorific'
import {ParagraphStyleBridge} from './bridges/paragraphStyle'
import {TextAlignBridge} from './bridges/textAlign'
import {TypographyBridge} from './bridges/typography'
import {UnderlineBridge} from './bridges/underline'
import {isAllowedColorValue} from './colorAllowlist'
import {DraftsButton} from './drafts/DraftsButton'
import {draftFacetsToEditorFacets} from './drafts/state/api'
import {
  useCleanupPublishedArticleDraftMutation,
  useSaveArticleDraftMutation,
} from './drafts/state/queries'
import {type ArticleDraftSummary} from './drafts/state/schema'
// Generated by `pnpm editor:build` - gitignored, run the build before this
// file will resolve (mirrors `TipTapSpike.tsx`'s own identical import).
import {editorHtml} from './editor-web/build/editorHtml'
import {
  articleDocumentToComposeState,
  type EditingArticleState,
} from './loadedArticle'
import {Metadata, type MetadataValue} from './Metadata'
import {type ParagraphStyleId} from './state'
import {Toolbar} from './Toolbar'

/**
 * `TenTapStartKit` minus its own default `UnderlineBridge`, plus this app's
 * own bridges - must mirror `AdvancedEditor.tsx`'s web `bridges` array
 * exactly by `.name` (confirmed via `RichText/utils.ts`:
 * `window.bridgeExtensionConfigMap` is built by reducing over *this* native
 * array, keyed by name - a bridge present on one side and missing on the
 * other silently loses its config entry, not a loud error). Bare
 * `@10play/tentap-editor` import is correct here, unlike the web bundle -
 * this is native RN code (Metro, real `react-native-webview` available),
 * the same import `TipTapSpike.tsx` already uses successfully; the `/web`
 * packaging bug and the `RichText`/`react-native-webview` Jest crash both
 * only ever affected the Vite web bundle and Jest respectively, never real
 * native code.
 */
const nativeBridgeExtensions = [
  ...TenTapStartKit.filter(bridge => bridge !== DefaultUnderlineBridge),
  UnderlineBridge,
  TextAlignBridge,
  TypographyBridge,
  HonorificBridge,
  ParagraphStyleBridge,
  ContentBridge,
]

/**
 * The article-authoring screen (`articles client ui plan.md` Phase 2). New
 * screen, not a composer extension - `Composer.tsx`'s reducer is shaped
 * entirely around post/thread/quote/reply semantics that don't apply here.
 * Desktop renders as a centered modal (matching the confirmed Figma design,
 * `58:4961`); mobile renders full-screen with an accordion metadata card
 * (`58:5153`/`58:5222`) - both share this same state and logic, only the
 * outer chrome differs.
 *
 * Self-contained - only needs an `onClose` callback. Registered as a plain
 * `Stack.Screen` (`ArticleComposeScreen` below adapts the two), mirroring
 * `StarterPackWizard`/`Wizard` rather than Composer's global-overlay
 * architecture - this component already draws its own full-bleed backdrop,
 * so it needs no extra screen-level chrome (`articles client ui plan.md`
 * Phase 3).
 */
export function ArticleCompose({
  onClose,
  initialArticle,
}: {
  onClose: () => void
  initialArticle?: LoadedArticleDocument
}) {
  const {_, i18n} = useLingui()
  const t = useTheme()
  const {gtMobile} = useBreakpoints()
  const pdsClient = usePdsClient()
  const appviewClient = useAppviewClient()
  const {currentAccount} = useSession()
  const queryClient = useQueryClient()
  const requireStriker = useRequireStrikerForArticleAuthoring()

  const [initial] = useState(() =>
    initialArticle
      ? articleDocumentToComposeState(initialArticle, {
          did: pdsClient.assertDid,
        })
      : undefined,
  )
  const [title, setTitle] = useState(initial?.title ?? '')
  const [subtitle, setSubtitle] = useState(initial?.subtitle ?? '')
  // `initialContent` is read once, at construction - later loads (draft
  // switching, clearing) go through `editorBridge.loadMarkdownAndFacets`
  // instead, never by changing this option after mount (TenTap doesn't
  // react to it).
  const editorBridge = useEditorBridge({
    customSource: editorHtml,
    bridgeExtensions: nativeBridgeExtensions,
    autofocus: false,
    avoidIosKeyboard: true,
    initialContent: initial?.editor ?? {markdown: '', facets: []},
    onChange: () => setBodyTouched(true),
  })
  const bridgeState = useBridgeState(editorBridge)
  // Approximates the old exact-content-equality `isDirty` check
  // (`JSON.stringify` of the full markdown string against a baseline
  // snapshot) with a simpler touched flag - the markdown itself is no
  // longer synchronously available (it lives inside the WebView, only
  // readable via `editorBridge.getMarkdownAndFacets()`, an async round
  // trip). Real, minor precision trade-off: typing something and then
  // undoing back to the exact original text now still reads as dirty,
  // where the old snapshot comparison would have caught the match. Reset
  // explicitly wherever the body's content is replaced wholesale
  // (`onClearComposer`/`onSelectDraft`) or the draft is freshly saved.
  const [bodyTouched, setBodyTouched] = useState(false)
  const [metadata, setMetadata] = useState<MetadataValue>(
    initial?.metadata ?? {
      authors: [],
      translators: [],
      categories: [],
      tags: [],
    },
  )
  const [coverImage, setCoverImage] = useState<
    site.standard.document.Main['coverImage']
  >(initial?.coverImage)
  const [coverImagePreviewUri, setCoverImagePreviewUri] = useState<
    string | undefined
  >(initial?.coverImagePreviewUri)
  const [flavor] = useState<'gfm' | 'commonmark'>(initial?.flavor ?? 'gfm')
  const [isPublishing, setIsPublishing] = useState(false)
  const [draftId, setDraftId] = useState<string | undefined>(undefined)
  const [draftUpdatedAt, setDraftUpdatedAt] = useState<string | undefined>(
    undefined,
  )
  const [editingArticle, setEditingArticle] = useState<
    EditingArticleState | undefined
  >(initial?.editingArticle)

  // Baseline-snapshot dirty tracking, not a reducer's per-action `isDirty`
  // flag like the post Composer's - there's no reducer here (plain
  // `useState` fields), and sprinkling `setIsDirty(true)` across every
  // handler is easy to miss one. Reset on mount, after a successful
  // save-to-draft, and after loading a selected draft. Covers
  // title/subtitle/metadata/coverImage only - the body's own dirtiness is
  // `bodyTouched` above, tracked separately since the markdown itself
  // isn't synchronously available to snapshot the way it used to be.
  //
  // `snapshotOf` takes explicit values rather than closing over
  // title/subtitle/metadata/coverImage directly, because the two handlers
  // below (`onClearComposer`/`onSelectDraft`) need to compute the new
  // baseline in the same synchronous call that calls `setTitle` etc. -
  // `setState` doesn't flush before the next line runs, so reading the
  // component's own state variables right after setting them would capture
  // the stale pre-update values, not what was just set.
  const snapshotOf = (v: {
    title: string
    subtitle: string
    metadata: MetadataValue
    coverImage: site.standard.document.Main['coverImage']
  }) => JSON.stringify(v)
  const snapshot = () => snapshotOf({title, subtitle, metadata, coverImage})
  const baselineRef = useRef(snapshot())
  const isDirty = bodyTouched || snapshot() !== baselineRef.current

  const hasContent =
    !!title.trim() ||
    !!subtitle.trim() ||
    !bridgeState.empty ||
    !!coverImage ||
    metadata.authors.length > 0 ||
    metadata.translators.length > 0 ||
    metadata.categories.length > 0 ||
    metadata.tags.length > 0

  const {mutateAsync: saveArticleDraft} = useSaveArticleDraftMutation()
  const {mutate: cleanupPublishedDraft} =
    useCleanupPublishedArticleDraftMutation()
  const discardPromptControl = Prompt.usePromptControl()
  const discardEditPromptControl = Prompt.usePromptControl()

  const onToggleMark = (mark: 'bold' | 'italic' | 'strikethrough') => {
    if (mark === 'bold') editorBridge.toggleBold()
    else if (mark === 'italic') editorBridge.toggleItalic()
    else editorBridge.toggleStrike()
  }

  const onToggleUnderline = () => editorBridge.toggleUnderline()

  const onSetColor = (hex: string) => {
    // Finding 20 enforcement point: the toolbar's own menu only ever offers
    // PRESET_COLORS, which already passes this trivially, but that's the
    // caller being well-behaved, not a structural guarantee. This is the
    // one place a #color.value actually gets constructed, so the allowlist
    // has to live here, not upstream - any future caller (a free-text color
    // input, say) is protected for free instead of having to remember to
    // re-check.
    if (!isAllowedColorValue(hex)) return
    editorBridge.setColor(hex)
  }

  const onSetAlign = (align: 'left' | 'center' | 'right' | 'justify') =>
    editorBridge.setTextAlign(align)

  const onInsertList = () => editorBridge.toggleBulletList()

  const onSelectParagraphStyle = (style: ParagraphStyleId) =>
    editorBridge.setParagraphStyle(style)

  const onInsertHonorific = (codepoint: number) =>
    editorBridge.insertHonorific(codepoint)

  // TipTap's `Link` mark applies over a selection, not at a bare cursor
  // position - matches TenTap's own `LinkBridge` state model exactly
  // (`canSetLink: !editor.state.selection.empty`), not a new restriction
  // this screen invents. The old placeholder-text-with-no-selection path
  // (`[link text](https://)`) doesn't have a clean equivalent under a real
  // mark-based schema, so this asks for a selection first instead - a
  // real, if minor, product behavior change worth calling out, not a
  // silent regression.
  const onInsertLink = () => {
    if (!bridgeState.canSetLink) {
      Toast.show(_(msg`Select some text first, then insert a link.`), {
        type: 'info',
      })
      return
    }
    editorBridge.setLink('https://')
  }

  const onInsertImage = async () => {
    const images = await openPicker({selectionLimit: 1})
    const image = images[0]
    if (!image) return
    const {blob} = await uploadBlob(pdsClient, image.path, image.mime)
    // com.atproto.sync.getBlob is a standard, unauthenticated atproto
    // endpoint (did+cid, both required) - a real, spec-compliant blob URL,
    // not a workaround. BlobRef is a union (current TypedBlobRef vs. the
    // legacy string-cid shape) - a freshly uploaded blob is always the
    // former, but narrow properly rather than assuming.
    const cid = 'ref' in blob ? blob.ref.toString() : blob.cid
    const url = `${SUNNAHSKY_SERVICE}/xrpc/com.atproto.sync.getBlob?did=${encodeURIComponent(pdsClient.assertDid)}&cid=${encodeURIComponent(cid)}`
    editorBridge.setImage(url)
  }

  const onPressCoverImage = async () => {
    const images = await openPicker({selectionLimit: 1})
    const image = images[0]
    if (!image) return
    const {blob} = await uploadBlob(pdsClient, image.path, image.mime)
    setCoverImage(blob)
    setCoverImagePreviewUri(image.path)
  }

  const doSaveDraft = async (): Promise<{success: boolean}> => {
    try {
      const {markdown, facets} = await editorBridge.getMarkdownAndFacets()
      const {draftId: savedId} = await saveArticleDraft({
        state: {
          title,
          subtitle,
          markdown,
          facets,
          metadata,
          coverImage,
        },
        existingDraftId: draftId,
      })
      setDraftId(savedId)
      setDraftUpdatedAt(new Date().toISOString())
      baselineRef.current = snapshot()
      setBodyTouched(false)
      return {success: true}
    } catch {
      Toast.show(_(msg`Couldn't save draft. Please try again.`), {
        type: 'error',
      })
      return {success: false}
    }
  }

  // Clears in-progress content back to a fresh empty draft, without closing
  // the screen - used by the header Drafts button's "Discard" path (Cancel's
  // own "Discard" instead closes the screen entirely, via onClose).
  const onClearComposer = () => {
    const empty = {
      title: '',
      subtitle: '',
      metadata: {authors: [], translators: [], categories: [], tags: []},
      coverImage: undefined,
    }
    setTitle(empty.title)
    setSubtitle(empty.subtitle)
    editorBridge.loadMarkdownAndFacets('', [])
    setMetadata(empty.metadata)
    setCoverImage(empty.coverImage)
    setCoverImagePreviewUri(undefined)
    setDraftId(undefined)
    setDraftUpdatedAt(undefined)
    // Defense-in-depth, not reachable in practice today - the Drafts UI
    // this is called from only renders when `!hasContent`, which is never
    // true while editing a published article.
    setEditingArticle(undefined)
    baselineRef.current = snapshotOf(empty)
    setBodyTouched(false)
  }

  const onSelectDraft = (summary: ArticleDraftSummary) => {
    const {draft} = summary
    const next = {
      title: draft.title ?? '',
      subtitle: draft.description ?? '',
      markdown: draft.markdown ?? '',
      metadata: {
        authors: draft.authors ?? [],
        translators: draft.translators ?? [],
        categories: draft.categories ?? [],
        tags: draft.tags ?? [],
      },
      coverImage: draft.coverImage,
    }
    setTitle(next.title)
    setSubtitle(next.subtitle)
    editorBridge.loadMarkdownAndFacets(
      next.markdown,
      draftFacetsToEditorFacets(draft.facets),
    )
    setMetadata(next.metadata)
    setCoverImage(next.coverImage)
    if (next.coverImage) {
      const cid =
        'ref' in next.coverImage
          ? next.coverImage.ref.toString()
          : next.coverImage.cid
      setCoverImagePreviewUri(
        `${SUNNAHSKY_SERVICE}/xrpc/com.atproto.sync.getBlob?did=${encodeURIComponent(pdsClient.assertDid)}&cid=${encodeURIComponent(cid)}`,
      )
    } else {
      setCoverImagePreviewUri(undefined)
    }
    setDraftId(summary.id)
    setDraftUpdatedAt(summary.updatedAt)
    // Defense-in-depth, not reachable in practice today - see the matching
    // note in `onClearComposer`.
    setEditingArticle(undefined)
    baselineRef.current = snapshotOf({
      title: next.title,
      subtitle: next.subtitle,
      metadata: next.metadata,
      coverImage: next.coverImage,
    })
    setBodyTouched(false)
  }

  const onPressCancel = () => {
    if (editingArticle) {
      if (isDirty) {
        discardEditPromptControl.open()
      } else {
        onClose()
      }
      return
    }
    if (hasContent && (!draftId || isDirty)) {
      discardPromptControl.open()
    } else {
      onClose()
    }
  }

  const doPublish = async () => {
    if (isPublishing || !title.trim() || bridgeState.empty) return
    if (editingArticle && !isDirty) return
    setIsPublishing(true)
    try {
      const {markdown, facets} = await editorBridge.getMarkdownAndFacets()
      const editing: ArticleEditRef | undefined = editingArticle
        ? {
            documentUri: editingArticle.uri,
            documentRkey: editingArticle.rkey,
            documentCid: editingArticle.cid,
            publishedAt: editingArticle.publishedAt,
            postUri: editingArticle.postUri,
            postRkey: editingArticle.postRkey,
          }
        : undefined
      const {postUri, documentUri} = await publishArticle({
        pdsClient,
        draft: {
          title: title.trim(),
          description: subtitle.trim() || title.trim(),
          markdown,
          flavor,
          facets,
          tags: metadata.tags,
          categories: metadata.categories.length
            ? metadata.categories
            : undefined,
          authors: metadata.authors.length ? metadata.authors : undefined,
          translators: metadata.translators.length
            ? metadata.translators
            : undefined,
          contributors: [],
          coverImage,
        },
        editing,
      })
      Toast.show(
        editingArticle
          ? _(msg`Article updated!`)
          : _(
              msg`Article published! It may take a few seconds to appear on your profile.`,
            ),
        {type: 'success'},
      )
      const did = currentAccount?.did
      if (did) {
        if (editingArticle) {
          void queryClient.invalidateQueries({queryKey: RQKEY(did)})
          void queryClient.invalidateQueries({
            queryKey: DOCUMENT_RQKEY(documentUri),
          })
        } else {
          // Best-effort: the AppView needs a moment to index the new
          // companion post before the Articles tab can resolve it (see
          // waitForArticleIndexed's doc comment). Not awaited - publish
          // should close immediately regardless of how long indexing takes.
          void waitForArticleIndexed(appviewClient, postUri).then(indexed => {
            if (indexed) {
              void queryClient.invalidateQueries({queryKey: RQKEY(did)})
            }
          })
        }
      }
      // Best-effort cleanup, matching the post Composer's own post-publish
      // draft cleanup - the article already published successfully, so a
      // failure here is logged, not surfaced (see the mutation's onError).
      // Unchanged by the edit-published-article mode: `draftId` and
      // `editingArticle` are mutually exclusive by construction, since the
      // Drafts UI is only reachable when `!hasContent`, never true here.
      if (draftId) {
        cleanupPublishedDraft({draftId})
      }
      onClose()
    } finally {
      setIsPublishing(false)
    }
  }
  const onPressPublish = requireStriker(() => void doPublish())

  // Both live-computed on the web side from `editor.getText()`/live editor
  // state and pushed here via the same debounced state-sync `useBridgeState`
  // already relies on for every other bridge - no separate polling, no
  // approximation the old ref-based cursor tracking needed.
  const wordCount = bridgeState.wordCount
  const charCount = bridgeState.charCount
  const activeParagraphStyle = bridgeState.activeParagraphStyle

  // Never "Save and close" while editing a published article - there's
  // deliberately no save-progress-without-publishing path for that mode
  // (see the plan's Context section), so the label would be misleading.
  const closeLabel =
    isDirty && !editingArticle ? _(msg`Save and close`) : _(msg`Close`)

  const content = (
    <View
      style={[
        a.flex_1,
        t.atoms.bg,
        gtMobile && [
          {
            width: 1000,
            maxWidth: '100%',
            height: '85%',
            minHeight: 480,
            maxHeight: 900,
          },
          a.rounded_md,
          a.overflow_hidden,
        ],
      ]}>
      <View
        style={[
          a.flex_row,
          a.align_center,
          a.justify_between,
          {paddingHorizontal: 18, paddingVertical: 12},
          a.border_b,
          t.atoms.border_contrast_low,
        ]}>
        <Pressable
          accessibilityRole="button"
          accessibilityLabel={closeLabel}
          accessibilityHint=""
          onPress={onPressCancel}>
          <Text
            style={[a.text_md, a.font_medium, {color: t.palette.primary_600}]}>
            {closeLabel}
          </Text>
        </Pressable>
        <View style={[a.flex_row, a.align_center, {gap: 18}]}>
          {!hasContent ? (
            <DraftsButton
              onSelectDraft={onSelectDraft}
              onSaveDraft={doSaveDraft}
              onDiscard={onClearComposer}
              hasContent={hasContent}
              isDirty={isDirty}
              isEditingDraft={!!draftId}
            />
          ) : editingArticle ? (
            <Text style={[a.text_sm, t.atoms.text_contrast_medium]}>
              <Trans>
                Published on{' '}
                {niceDate(i18n, editingArticle.publishedAt, 'medium', 'none')}.
              </Trans>
              {editingArticle.updatedAt && (
                <Trans>
                  {' '}
                  Last Modified:{' '}
                  {niceDate(i18n, editingArticle.updatedAt, 'medium', 'none')}.
                </Trans>
              )}
              {isDirty && <Trans> • Unsaved edits.</Trans>}
            </Text>
          ) : draftId && !isDirty ? (
            <Text style={[a.text_sm, t.atoms.text_contrast_medium]}>
              <Trans>
                Draft saved{' '}
                {niceDate(
                  i18n,
                  draftUpdatedAt ?? new Date().toISOString(),
                  'medium',
                  'none',
                )}
                .
              </Trans>
            </Text>
          ) : (
            <Text style={[a.text_sm, t.atoms.text_contrast_medium]}>
              <Trans>Unsaved draft.</Trans>
            </Text>
          )}
          <Button
            label={editingArticle ? _(msg`Update`) : _(msg`Publish`)}
            variant="solid"
            color="primary"
            size="small"
            disabled={
              isPublishing ||
              !title.trim() ||
              bridgeState.empty ||
              (!!editingArticle && !isDirty)
            }
            onPress={onPressPublish}>
            <ButtonText>
              {isPublishing ? (
                editingArticle ? (
                  <Trans>Updating...</Trans>
                ) : (
                  <Trans>Publishing...</Trans>
                )
              ) : editingArticle ? (
                <Trans>Update</Trans>
              ) : (
                <Trans>Publish</Trans>
              )}
            </ButtonText>
          </Button>
        </View>
      </View>

      <Prompt.Outer control={discardPromptControl}>
        <Prompt.Content>
          <Prompt.TitleText>
            {draftId ? (
              <Trans>Save changes?</Trans>
            ) : (
              <Trans>Save draft?</Trans>
            )}
          </Prompt.TitleText>
          <Prompt.DescriptionText>
            {draftId ? (
              <Trans>
                You have unsaved changes to this draft, would you like to save
                them?
              </Trans>
            ) : (
              <Trans>
                Would you like to save this as a draft to edit later?
              </Trans>
            )}
          </Prompt.DescriptionText>
        </Prompt.Content>
        <Prompt.Actions>
          <Prompt.Action
            cta={draftId ? _(msg`Save changes`) : _(msg`Save draft`)}
            onPress={() =>
              void doSaveDraft().then(({success}) => {
                if (success) onClose()
              })
            }
            color="primary"
          />
          <Prompt.Action
            cta={_(msg`Discard`)}
            onPress={onClose}
            color="negative_subtle"
          />
          <Prompt.Cancel cta={_(msg`Keep editing`)} />
        </Prompt.Actions>
      </Prompt.Outer>

      <Prompt.Basic
        control={discardEditPromptControl}
        title={_(msg`Discard changes?`)}
        description={_(
          msg`You have unsaved edits to this article. If you close now, they will be lost.`,
        )}
        onConfirm={onClose}
        confirmButtonCta={_(msg`Discard`)}
        confirmButtonColor="negative"
        cancelButtonCta={_(msg`Keep editing`)}
      />

      <Metadata
        value={metadata}
        onChange={setMetadata}
        coverImagePreviewUri={coverImagePreviewUri}
        onPressCoverImage={() => void onPressCoverImage()}
      />

      <View style={[a.flex_1, {padding: 18}, a.gap_md]}>
        <Toolbar
          onToggleMark={onToggleMark}
          onToggleUnderline={onToggleUnderline}
          activeParagraphStyle={activeParagraphStyle}
          onSelectParagraphStyle={onSelectParagraphStyle}
          onInsertList={onInsertList}
          onSetAlign={onSetAlign}
          onSetColor={onSetColor}
          onInsertHonorific={onInsertHonorific}
          onRequestBodyFocus={() => {
            // Regains WebView focus without repositioning the cursor -
            // `null` matches TipTap's own "focus without moving the
            // selection" convention. Unlike the old plain-`TextInput`
            // model, there's no caret position to manually restore here:
            // `HonorificBridge`'s own `onBridgeMessage` already does
            // `.chain().focus().insertContent(text).run()` on the web
            // side, in the same transaction as the insert, so the cursor
            // is already exactly where it should be by the time this runs.
            editorBridge.focus(null)
          }}
          onInsertLink={onInsertLink}
          onInsertImage={() => void onInsertImage()}
        />

        <View
          style={[
            a.flex_1,
            a.border,
            a.rounded_md,
            t.atoms.border_contrast_low,
            {padding: 20, gap: 16},
          ]}>
          {/*
           * Plain TextInput, not TextField.Input, for all three fields -
           * Figma shows Title/Sub-title/Body as borderless typography with
           * no input-box chrome, matching Body's existing pattern exactly
           * (confirmed by auditing TextField.tsx: neither field uses
           * isInvalid, so no chrome/validation feature is lost by skipping
           * it - see `articles client ui plan.md`/the ArticleCompose Figma
           * plan for the full audit). TextField.Input's fontFamily is also
           * unconditionally overwritten by applyFonts(), which would
           * silently clobber the custom article fonts below.
           */}
          {/* Own nested group with a tighter 12px gap (space-lg) - the
          outer 16px gap (space-lg... the OTHER space-lg, Figma's two
          differently-scoped spacing tokens) is between this group and Body. */}
          <View style={[{gap: 12}]}>
            <TextInput
              accessibilityLabel={_(msg`Title`)}
              accessibilityHint=""
              defaultValue={title}
              onChangeText={setTitle}
              placeholder={_(msg`Article title...`)}
              placeholderTextColor={t.palette.contrast_500}
              style={[
                {
                  // Baked into the static instance's own name table, not
                  // "Fraunces" + fontWeight - see assets/fonts/fraunces/README.md.
                  fontFamily: 'Fraunces SemiBold',
                  fontSize: 32,
                  lineHeight: 32 * 1.15,
                  padding: 0,
                  margin: 0,
                },
                t.atoms.text,
              ]}
            />
            <TextInput
              accessibilityLabel={_(msg`Sub-title`)}
              accessibilityHint=""
              defaultValue={subtitle}
              onChangeText={setSubtitle}
              placeholder={_(msg`Sub-title (optional)...`)}
              placeholderTextColor={t.palette.contrast_500}
              style={[
                {
                  fontFamily: 'Archivo SemiBold',
                  fontSize: 24,
                  lineHeight: 24 * 1.2,
                  padding: 0,
                  margin: 0,
                },
                t.atoms.text,
              ]}
            />
          </View>
          {/*
           * The body editor itself - previously a plain multiline
           * `TextInput` holding raw markdown text; now the real TipTap
           * WYSIWYG editor, rendered into a native WebView via
           * `customSource` (`AdvancedEditor.tsx`, bundled separately by
           * Vite). Fonts/placeholder styling live in the web bundle's own
           * CSS now, not as RN style props here - there's no RN text node
           * to style directly once content renders inside the WebView.
           */}
          <RichText editor={editorBridge} style={[a.flex_1]} />
        </View>
        <Text style={[a.text_sm, t.atoms.text_contrast_medium]}>
          <Trans>
            Word count: {wordCount} • Character count: {charCount}
          </Trans>
        </Text>
      </View>
    </View>
  )

  return (
    <ComposerOverlay onPressCancel={onPressCancel}>{content}</ComposerOverlay>
  )
}

/**
 * Shared full-bleed backdrop/Portal chrome for `ArticleCompose` - desktop
 * centered modal vs. mobile full-screen, per the confirmed Figma design.
 * Extracted so `ArticleEditLoadingGate` below can share the exact same
 * chrome instead of duplicating it, rather than rendering unstyled while an
 * article loads.
 */
function ComposerOverlay({
  children,
  onPressCancel,
}: {
  children: React.ReactNode
  onPressCancel?: () => void
}) {
  const {_} = useLingui()
  const t = useTheme()
  const {gtMobile} = useBreakpoints()

  if (gtMobile) {
    return (
      <Portal>
        <View
          style={[
            a.fixed,
            a.inset_0,
            // No explicit z-index, deliberately - this wrapper and any
            // Dialog.Outer/Prompt.Outer opened from within it (e.g.
            // DraftsListDialog) render as siblings through the same shared
            // Portal/Outlet. Dialog.Outer's own outer wrapper computes to an
            // *explicit* z-index:0 (not auto), which creates its own
            // stacking context - meaning ANY explicit z-index here, even a
            // small one, would always out-rank it regardless of DOM order,
            // trapping the dialog's real z-index (10) inside a losing
            // sibling subtree where it's never actually compared. Leaving
            // this at the implicit z-index:auto lets normal DOM order decide
            // instead: a dialog opened later mounts later in the DOM and
            // correctly wins, the same mechanism that already makes stacked
            // dialogs work everywhere else in the app. Still reliably paints
            // above the base app screen behind it - `position: fixed` alone
            // is enough for that, since the base screen isn't independently
            // positioned/z-indexed to begin with.
            a.align_center,
            a.justify_center,
            {backgroundColor: 'rgba(0,0,0,0.75)'},
            web({
              paddingTop: '50px' as unknown as number,
              paddingBottom: '50px' as unknown as number,
            }),
          ]}>
          {children}
        </View>
      </Portal>
    )
  }

  return (
    <Portal>
      <View style={[a.absolute, a.inset_0, t.atoms.bg]}>
        {children}
        {onPressCancel && (
          <Pressable
            accessibilityRole="button"
            accessibilityLabel={_(msg`Cancel`)}
            accessibilityHint=""
            onPress={onPressCancel}
            style={[a.absolute, {top: 12, right: 12}, a.p_sm]}>
            <XIcon width={20} style={[t.atoms.text_contrast_medium]} />
          </Pressable>
        )}
      </View>
    </Portal>
  )
}

/**
 * `Stack.Screen` adapter - see the doc comment on `ArticleCompose` above.
 * Shared between `ArticleCompose` (create) and `ArticleEdit` (edit an
 * already-published article) - mirrors `StarterPackWizard`/`StarterPackEdit`
 * sharing `Wizard`. `rkey` is only ever present for the edit route; the
 * document URI it derives always uses the *current signed-in account's own*
 * DID, never anything route-suppliable, so this can never load another
 * account's article regardless of what `rkey` a deep link supplies.
 */
export function ArticleComposeScreen({
  route,
}: NativeStackScreenProps<
  CommonNavigatorParams,
  'ArticleCompose' | 'ArticleEdit'
>) {
  // `useNavigation<NavigationProp>()`, not the screen's own narrower
  // `navigation` prop - mirrors `Layout.Header.BackButton`'s `onPressBack`
  // exactly, which needs the app-wide route union (including `Home`) that
  // the stack-scoped prop type doesn't expose.
  const navigation = useNavigation<NavigationProp>()
  const {currentAccount} = useSession()
  const params = route.params ?? {}
  const rkey: string | undefined =
    'rkey' in params && typeof params.rkey === 'string'
      ? params.rkey
      : undefined
  const uri: AtUriString | undefined = rkey
    ? `at://${currentAccount!.did}/site.standard.document/${rkey}`
    : undefined
  const {
    data: initialArticle,
    isLoading,
    isError,
    refetch,
  } = useArticleDocumentQuery(uri)

  const onClose = () => {
    // `goBack()` silently no-ops if there's nothing in history to pop
    // (e.g. a direct URL load/refresh). Unlike `BackButton`'s fallback,
    // this uses `replace` rather than `navigate`: on a cold direct-URL
    // load, Home isn't in `state.routes` yet, so `navigate('Home')`
    // would *push* it on top instead of jumping to an existing entry -
    // leaving this route's own entry (and therefore its still-mounted,
    // still-visible component, per the LRU mount-caching in
    // `createNativeStackNavigatorWithAuth`) sitting right underneath.
    // `replace` removes this route from the stack outright, so it
    // actually unmounts instead of lingering as a phantom "back"
    // target for the next Cancel press.
    if (navigation.canGoBack()) {
      navigation.goBack()
    } else {
      navigation.replace('Home')
    }
  }

  if (rkey && (isLoading || (!initialArticle && !isError))) {
    return (
      <ArticleEditLoadingGate
        isError={false}
        onClose={onClose}
        onRetry={() => void refetch()}
      />
    )
  }
  if (rkey && (isError || !initialArticle)) {
    return (
      <ArticleEditLoadingGate
        isError
        onClose={onClose}
        onRetry={() => void refetch()}
      />
    )
  }

  return <ArticleCompose onClose={onClose} initialArticle={initialArticle} />
}

function ArticleEditLoadingGate({
  isError,
  onClose,
  onRetry,
}: {
  isError: boolean
  onClose: () => void
  onRetry: () => void
}) {
  const {_} = useLingui()
  const t = useTheme()
  return (
    <ComposerOverlay onPressCancel={onClose}>
      <View
        style={[
          a.flex_1,
          a.align_center,
          a.justify_center,
          t.atoms.bg,
          {gap: 16},
        ]}>
        {isError ? (
          <>
            <Text
              style={[a.text_md, a.text_center, t.atoms.text_contrast_medium]}>
              <Trans>Couldn't load this article.</Trans>
            </Text>
            <Button
              label={_(msg`Retry`)}
              variant="solid"
              color="primary"
              size="small"
              onPress={onRetry}>
              <ButtonText>
                <Trans>Retry</Trans>
              </ButtonText>
            </Button>
          </>
        ) : (
          <Loader size="xl" />
        )}
      </View>
    </ComposerOverlay>
  )
}
